language: node_js
node_js:
  - "9.1.0"
sudo: required 
dist: trusty
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update
install: 
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  - nvm install 9.1.0
  - npm install electron --save-dev
script:
  - node -v
  - npm -v
  - npm install
